version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rails/takuya-app4
    overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/restart_server
      timeout: 300
      runas: root